
services:
  redis:
    container_name: mud-redis
    image: 'redis:alpine'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '6379:6379'

  server:
    container_name: server
    image: ninthsun91/mud-server:${VERSION}.${SUB_VERSION}
    restart: always
    build:
      context: main_server
      dockerfile: ./Dockerfile
    env_file:
      - ./main_server/.env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3333:3333'

  battle:
    container_name: battle
    image: ninthsun91/mud-battle:${VERSION}.${SUB_VERSION}
    restart: always
    build:
      context: battle_server
      dockerfile: ./Dockerfile
    env_file:
      - ./battle_server/.env
    environment:
      - BATTLE_PORT=3500
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3500:3500'
    depends_on:
      - server

  pvp:
    container_name: pvp
    image: ninthsun91/mud-pvp:${VERSION}.${SUB_VERSION}
    restart: always
    build:
      context: pvp_server
      dockerfile: ./Dockerfile
    env_file:
      - ./pvp_server/.env
    environment:
      - PVP_PORT=3600
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3600:3600'
    depends_on:
      - server

  front:
    container_name: front
    image: ninthsun91/mud-front:${VERSION}.${SUB_VERSION}
    restart: always
    build:
      context: front_server
      dockerfile: ./Dockerfile
    env_file:
      - ./front_server/.env
    environment:
      - FRONT_PORT=3400
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3400:3400'
    depends_on:
      - server

  web:
    container_name: web
    image: ninthsun91/mud-web:${VERSION}.${SUB_VERSION}
    restart: always
    build:
      context: web_server
      dockerfile: ./Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - WEB_PORT=8080
    ports:
      - '8080:8080'
    depends_on:
      - server

  was-lb:
    container_name: was-lb
    image: ninthsun91/mud-waslb:${VERSION}.${SUB_VERSION}
    restart: always
    build: was_lb
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
    depends_on:
      - server
      - front
      - battle
      - pvp
