
services:
  redis:
    image: 'redis:alpine'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '6379:6379'

  server:
    image: ninthsun91/mud-server:${VERSION}
    build:
      context: main_server
      dockerfile: ./Dockerfile
    env_file:
      - ./main_server/.env

  battle:
    image: ninthsun91/mud-battle:${VERSION}
    build:
      context: battle_server
      dockerfile: ./Dockerfile
    env_file:
      - ./battle_server/.env

  pvp:
    image: ninthsun91/mud-pvp:${VERSION}
    restart: always
    build:
      context: pvp_server
      dockerfile: ./Dockerfile
    env_file:
      - ./pvp_server/.env

  front:
    image: ninthsun91/mud-front:${VERSION}
    restart: always
    build:
      context: front_server
      dockerfile: ./Dockerfile
    env_file:
      - ./front_server/.env

  web:
    image: ninthsun91/mud-web:${VERSION}
    restart: always
    build:
      context: web_server
      dockerfile: ./Dockerfile

  was-lb:
    image: ninthsun91/mud-waslb:${VERSION}
    restart: always
    build: was_lb
